server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass https://lista-tarefas-back.onrender.com/;
    proxy_set_header Host lista-tarefas-back.onrender.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
    proxy_ssl_name lista-tarefas-back.onrender.com;
    # Force a trusted Origin for upstream to avoid backend rejecting preflight
    proxy_set_header Origin http://localhost:8080;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}